### ISSUE TITLE
Remove / create identities

### ISSUE THREAD

**Issue by Phylon** [Sirrix-AG/PanBox#28]
Hello,

I am new to PanBox.
I did install it and it seems to work so far (windows).
According to the manual I cannot change the e-mail address of my identity.
My problem is: I don't even find a way how to delete my identity and create a new one.
Or alternatively, create a second one to be able to use different e-mail addresses.
Does anyone have a clue for me?
Additionally, I propose that PanBox creates new directories for new shares automatically, when the given name does not exist.
Thanks.

**Comment by caschulz88** [comment]
Hi Phylon,

thanks for giving feedback. Since removing identity also means total loss of any data that has been encrypted with this key material in case you have just one computer using this identity this sounds more like a very special corner case.

Currently PanBox just works with one identity. So in case you have multiple Dropbox accounts for example you will need to manage these things manually by renaming the .panbox folder in your home directory to .panbox.dropbox1 and start PanBox again so that a separated identity will be created. Every time you would like to switch between both identities you would need to rename the correct identity folder to .panbox so that PanBox can access the correct key material.

But using one PanBox identity also works with multiple Dropbox accounts. The only disadvantage here is that shares will be needed to add again to PanBox once you changed your Dropbox account in the background since PanBox will try to access share folder paths that do not exist anymore.

In general the email address in PanBox is just a comfort feature. You can enter any email address you want to. This email address is just used in case someone else wants to send you a share invitation. In case the email is wrong the other user would need to type the correct one manually, by adding an addition cloud storage provider account for your contact.

Creating directories automatically is a good thing I guess and would help to improve usability. I will try to add this feature as soon as possible so that is can also be part of version 1.1 PanBox release. Thanks!

**Comment by Phylon** [comment]
Hello caschulz88,

thanks for your quick reply, this information helps.
I did not know that the e-mail address is just a comfort feature. I had in mind that some people might want to have a real name identity to share data with close friends and another one to share data with people in a forum, for example, using the pseudonym they have chosen for the forum.
I would also like to mention something else. There is a little usability issue with the configuration utility.
When you just set the checkmark for logging  without touching the drive letter list the standard "P" drive letter is lost after reboot and you have to go through the whole cycle again. Since the the letter is not in the list while it is in use, it is not possible to deliberately select it in order to keep it, when you just want to switch logging on/off.
Thanks again!

**Comment by caschulz88** [comment]
Hi again,

for your information. In version 1.1 the whole configuration utility on Windows is gone since we already did a lot of work on the whole Windows client architecture. It feels way smoother now and we don't have this extra step of Windows service anymore there - so we also don't need reboots on installation/deinstallation and every user can specify his own PanBox drive directly on the configuration tab in PanBox application.

Thanks! If you have any other issues or questions feel free to contact us!

**Comment by Phylon** [comment]
Thanks!
I am eager to give the new version a shot!
