### ISSUE TITLE
Creating shares on WEBDAV-Drive does not work

### ISSUE THREAD

**Issue by Phylon** [Sirrix-AG/PanBox#30]
Hello,

I cannot create a share on a mapped webdav-drive (Windows7-64).
After entering directory and password, I only get the error message
"An error occurred while adding the share to Panbox." I have no idea what kind of error this might be.
There is no information about using webdav-drives in the manual.
Some additional information would be appreciated.
Thanks.

**Comment by caschulz88** [comment]
Hi, is your WebDAV drive a common Windows drive/network drive? In the version 1.0 there were some architectural decisions which makes needs a workaround to use a WebDAV drive on Windows. These will be changed in version 1.1 (the changes are already part of the gitlab repository code).

We have a FAQ entry about this issue, but I guess you haven't found it yet because it's just in German available.

Run an administrator user a cmd and execute psexec -i -d -s cmd. This will open a new cmd as NT-Authority/SYSTEM user. You can download psexec from https://technet.microsoft.com/de-de/sysinternals/bb897553.aspx

Afterwards enter these commands (with edited paths) to the command line running as NT-Authority/SYSTEM user:

net use \\<WebDAV>\<Share-name>
mklink /D C:\<Path> \\\<WebDAV>\<Share-name>

If existing remove the existing .panbox folder. Afterwards you can setup your PanBox share using the PanBox client and the C:\<Path>.

This workaround will create a symbolic link from the original location to the C:\<Path> folder as NT-Authority/SYSTEM user. This is needed since the PanBox windows service runs as NT-Authority/SYSTEM user and also need access to the PanBox share to read/write data to it. This service does not work anymore in next versions so that this workaround is only needed for Version 1.0.

Hope this helps! If you have further questions feel free to ask.

**Comment by Phylon** [comment]
Hello,

thank you for your quick response. Unfortunately, this workaround did not work for me.
The only difference to my previous attempt to create a share is a different error message.
It says "Error while accessing share metadata!", not much more self-explanatory than the 
other one. Since the next version will be quite different, as you have described, it might be
better to wait for 1.1 instead of putting much effort into getting the old version working.
Thanks.

**Comment by caschulz88** [comment]
User will wait for version 1.1

**Comment by Phylon** [comment]
Hello,

I just tried version 1.1.1. It seems my WEBDAV-drive (OS: W7-64) is working with the new version. It is pretty slow, of course. If performance is an issue, a local mirror is certainly recommended.
Thanks so far!

**Comment by caschulz88** [comment]
Good to know and thanks for the positive feedback! :smiley:
