### ISSUE TITLE
Compatibility to Owncloud / Pairing problem

### ISSUE THREAD

**Issue by bcu8heq2** [Sirrix-AG/PanBox#74]
Panbox seems to depend entirely on Dropbox. I have not found a possibility to share an owncloud folder on two PCs. One is running Linux, one Win7. Panbox does not offer any option to indicate that the owncloud folder is the cloud folder instead of the dropbox folder. I can set up share on either machine but the other one will notice nothing of that even though I linked the devices and granted permission for them in Panbox. No wonder I guess though because how would Panbox know where to find the cloud folder with the encrypted share? However, the descriptions I found on the web state that Panbox works with any cloud solution. I got that wrong?

**Comment by caschulz88** [comment]
Hi,

I guess you are mixing two things here. PanBox is indeed fully compatible to every cloud storage provider who provides an automatically synced folder, like Google Drive, Microsoft OneDrive, and many others. PanBox provides two separate types of shares. Only when working with Dropbox shares you will have to specify some Dropbox folder in the configuration tab and use the share type Dropbox when creating a new share or adding an existing one. When working with any other share type like OwnCloud you will have to choose "Folder" share type. In next step you can then specify the full path to the folder of the newly created share on your system. This should be an empty folder in the synchronization folder of OwnCloud - Or better (I guess you can use network path integration on a Windows system): You can directly enter the network path as folder path like: \\owncloud\sharename.

When this share have been created on one machine you can easily add it on your other device after setting permissions on it for the other device. Simply add the existing share again as "Folder" share type in the GUI. PanBox will detect that the share already exists and will add it to the share list instead of creating a new one. So the add function is used for creating new shares AND for adding existing shares.

Please note that you will need PanBox 1.1.2 for the network path support in Windows. For PanBox 1.0.0 you would have to use some workaround (this one was also mentioned on the official FAQ), which is not needed in version 1.1.2 anymore.

Hope this description helps. Otherwise feel free to contact us again.

**Comment by bcu8heq2** [comment]
Thanx for your quick response. I understand the difference between Dropbox and Folder sync. However, I was not sure whether the folder has to be in the syncing owncloud folder. Seemed logical but it should be better documented. I think what confused me is that the folder for the share has to be empty. So let's say I have managed to sync and share a folder with Owmcloud and Panbox but now want to add another device. This does not work, if the shared folder is not empty correct?

Thanx again.

Am 29. Februar 2016 09:09:28 MEZ, schrieb Clemens Alexander Schulz <notifications@github.com>:

**Comment by bcu8heq2** [comment]
Sorry, I meant I was not sure whether the "Panbox-Folder" needs to be in the owncloud sync folder or not. The share surely needs to be in there though. I created a share in the synced owncloud folder, gave permissions for the other machine and tried to add the same folder as a share on it. It says the folder needs to be empty so I moved the content out of it and then a password query appeared. After that it says it fails because the device has no permission. I assume thisis because it is a slave, not a master. So how would shares appear on slaves then?

Am 29. Februar 2016 09:09:28 MEZ, schrieb Clemens Alexander Schulz <notifications@github.com>:

**Comment by caschulz88** [comment]
Hi, the detection of master and slave is PanBox internally and should not be the issue here. Let me please explain you what should be done and what should be expected there:

1. Create a new empty folder in your owncloud share
2. Add this empty folder to PanBox by adding a new share in the list of shares.
-> Check if the share was created in the backend directory. Simply open the specified location in the explorer for example. There must be a ".panbox"-folder, which contains certain metadata files of the share.
3. Give the other device permission to this share.
4. Check on the other device if the share exists there in the back. Also check this in the explorer and compare the files from the first device. It might be possible that for example by default the ".panbox"-folder isn't synchronized as folders which starts with a dot are blacklisted. This is default behavior for some synchronization clients.
5. If you are sure that the files are exactly the same on both machines on the backend add it to PanBox.
-> Add the Folder share with the same backend-folder in PanBox app. Of course the folder won't be empty there anymore as the .panbox-folder, which describes this folder to be a PanBox share is already in there and it must stay in there! If you move this folder out of the PanBox share PanBox won't be able to recognize this folder to be a PanBox share.

I guess that there is an issue with the synchronization of files in your owncloud backend. Please check if this is the case. Thanks and feel free to contact us if you have any further questions.

**Comment by bcu8heq2** [comment]
I just tried what you suggested and indeed owncloud did not sync the hidden files and folders. Yet, when try to add the share it now says that the owner of the share is unknown and that I should add the owner to my address book. That's kind of strange because there is just one identity but two devices so no new identity to add here. I of course linked the two devices with each other. I realized something strange though: The fingerprints of the encryption and the signature key could be messed up. The encryption key of device A is the signature key on device B and the encryption key of device B is the signature key of device A. Shouldn't they match?

**Comment by caschulz88** [comment]
Hi, thanks for the replay! You just ran into a bug, which has been resolved already on git master. You seem to execute a LAN/WLAN/Bluetooth pairing of both devices. When pairing a desktop slave machine via LAN/WLAN/Bluetooth you are exactly running into this issue. Please execute a file pairing instead to resolve this issue. You can pair your second machine again by removing the ".panbox"-folder in your profile like C:\Users\<Username>\.panbox or /home/<username>/.panbox on a Linux machine.

As you are the second user who ran into this issue I will release a version 1.1.3 at the end of this week, which will resolve this issue for Linux and Windows. Even with this new version you would need to re-execute the pairing of your second computer.

Please close this issue as soon as you can confirm that everything works now after the new pairing as file-pairing.

**Comment by bcu8heq2** [comment]
I just followed your instructions and paired my devices by using the file option. Everything looks fine now. The crypto keys match now, shares get added as they should and syncing works. Seems like it was this pairing issue that you describe above. Thanx! I'll close this issue.

**Comment by caschulz88** [comment]
Nice to hear everything is working now! If you have any further questions or issues feel free to contact us.
